name: CI pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  pipeline_name:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Static Analysis
      run: |
        echo "Formatting code"
        black src 
        black tests 
        echo "Linting code"
        ruff src 
        ruff tests 
        echo "Running static analysis"
        mypy src 
        mypy tests 

    - name: Run Tests
      run: |
        echo "Running Tests"
        pytest -v tests/ --junitxml=test-reports/tests_report.xml

    - name: Generate Test Coverage Report
      run: |
        echo "Generating Test Coverage Report"
        pytest --cov --cov-report=html:test-reports/coverage-report.html

    - name: Run Script
      run: |
        python src/main.py

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: output/test-reports/
